[programs.devnet]
hydra_solana_anchor = "G17Xqi5vxArztd7w1ScgYF1YcYCqf5wcLFDRLd9hQ7Lh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/vietbui/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
